### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by fdx-xdf** [joaoviictorti/RustRedOps#3]
Sorry, can you write some examples of global_asm, such as syscall, I'm in big trouble, thank you!

**Comment by joaoviictorti** [comment]
Hi @fdx-xdf, I have the code that performs this kind of action on my local computer and I'm going to upload it in a few days. I was focused on some projects related to the Windows kernel, writing some drivers in rust, but I will certainly upload this.

**Comment by fdx-xdf** [comment]
Thank you so much.I'm looking forward to your code.

**Comment by joaoviictorti** [comment]
Hi, @fdx-xdf!

I've added the code you mentioned. Please check that it's as expected. At the moment, I've only included support for x64. In the future, I may add support for x86 if necessary.

I left it inside the `Syscalls` folder, replaced the code that was there with the one I have now.

**Comment by fdx-xdf** [comment]
I checked out the code and that is indeed what I want, thanks again for your selfless open source spirit!
Good luck.
